FROM golang:alpine

MAINTAINER sine "sinerwr@gmail.com"

RUN apk --update add git && \
    go-wrapper download github.com/SiCo-Ops/B && \
    git checkout develop && \
    apk del git && \
    cd $GOPATH/src/github.com/SiCo-Ops/B && \
    go-wrapper install && \
    wget https://s3.amazonaws.com/sico-ops/config.sample.json -O $GOPATH/bin/config.json && \
    cd $GOPATH/bin &&\
    rm -rf $GOPATH/src

EXPOSE 6666

WORKDIR $GOPATH/bin

CMD ["B"]